version: "3.8"

services:
  # php:
  #   image: php:8.2-fpm-alpine
  #   restart: always
  #   volumes:
  #     - ./:/var/www/html
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    # ports:
    #   - 5173:5173

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    depends_on:
      - web
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432
