version: "3.8"

services:
  db:
    container_name: laravel-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  web:
    container_name: laravel-web
    restart: always
    build: .
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  nginx:
    container_name: laravel-nginx
    build: ./.docker/nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    depends_on:
      - web
